"""init forecast history

Revision ID: 70c8941012ca
Revises:
Create Date: 2026-02-28 20:53:30.146649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70c8941012ca"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolve_at", sa.DateTime(), nullable=False),
        sa.Column("resolution_criteria", sa.String(), nullable=False),
        sa.Column("resolution_source_policy", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "resolved_yes", "resolved_no", "void", name="questionstatus"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by", sa.String(), nullable=True),
        sa.Column("resolution_notes", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_table(
        "sources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("publisher", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("credibility_score", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_url"), "sources", ["url"], unique=False)

    op.create_table(
        "evidence_items",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("indicator_type", sa.String(), nullable=False),
        sa.Column("direction", sa.Integer(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_items_question_id"),
        "evidence_items",
        ["question_id"],
        unique=False,
    )

    op.create_table(
        "forecasts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("probability", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("method_version", sa.String(), nullable=False),
        sa.Column("explanation_md", sa.String(), nullable=False),
        sa.Column("inputs_hash", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_forecasts_question_id"), "forecasts", ["question_id"], unique=False)

    op.create_table(
        "evidence_sources",
        sa.Column("evidence_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("claim_excerpt", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence_items.id"]),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"]),
        sa.PrimaryKeyConstraint("evidence_id", "source_id"),
    )

    op.create_table(
        "forecast_evidence",
        sa.Column("forecast_id", sa.String(), nullable=False),
        sa.Column("evidence_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence_items.id"]),
        sa.ForeignKeyConstraint(["forecast_id"], ["forecasts.id"]),
        sa.PrimaryKeyConstraint("forecast_id", "evidence_id"),
    )

    op.create_table(
        "forecast_sources",
        sa.Column("forecast_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("claim_excerpt", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["forecast_id"], ["forecasts.id"]),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"]),
        sa.PrimaryKeyConstraint("forecast_id", "source_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forecast_sources")
    op.drop_table("forecast_evidence")
    op.drop_table("evidence_sources")
    op.drop_index(op.f("ix_forecasts_question_id"), table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_index(op.f("ix_evidence_items_question_id"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_sources_url"), table_name="sources")
    op.drop_table("sources")
    op.drop_table("questions")
    # ### end Alembic commands ###
