name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: transiv
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd ~/prognostic-fullstack
          git pull origin main
          docker compose build backend frontend
          docker stop forecast-frontend forecast-backend
          docker rm forecast-frontend forecast-backend
          docker compose up -d backend frontend
